version: "3.9"

services:
  social-api:
    build: .
    container_name: social-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: social-db
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: social-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "rG2k5@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
