version: "3.9"

services:
  social-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: social-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: social-db
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pg-adminer:
    image: adminer:latest
    container_name: social-adminer
    ports:
      - "1080:8080"
    environment:
      # Optional: Prefills the 'Server' field in the login screen
      ADMINER_DEFAULT_SERVER: postgres 
    depends_on:
      - postgres

volumes:
  pgdata:
